/**
 * Workforce Strength & AI Upskilling (HITL Transition) Module
 */

/**
 * Baseline role database detailing automation vulnerabilities and HITL upskilling routes
 */
const ROLE_TEMPLATES = {
  // Food & Catering
  'general manager': {
    category: 'Operations',
    automationRisk: 0.30,
    currentLiteracy: 'Medium',
    hitlTitle: 'AI-Enabled Operations Director',
    impact: '40% acceleration in scheduling, menu deployment, and local outreach.',
    trainingWeeks: 4,
    skillsNeeded: ['Process Automation (Make.com)', 'AI Customer Communication', 'Staffing Optimization'],
    transitionSteps: [
      'Automate employee shift scheduling using AI heuristic planners.',
      'Deploy AI review-routing tools to monitor and reply to local listings feedback.',
      'Leverage AI tools for drafting supplier agreements and promotional schedules.',
      'Analyze seasonal demand forecasts generated by business intelligence models.'
    ]
  },
  'kitchen manager': {
    category: 'Food Operations',
    automationRisk: 0.25,
    currentLiteracy: 'Low',
    hitlTitle: 'AI Inventory & Kitchen Coordinator',
    impact: '50% reduction in manual food inventory tracking and ingredient waste.',
    trainingWeeks: 4,
    skillsNeeded: ['AI Inventory Tracking', 'Conversational Procurement Tools', 'Recipe Costing Models'],
    transitionSteps: [
      'Implement AI OCR receipt scanners to automatically verify ingredient supplier invoices.',
      'Utilize natural language query interfaces to search kitchen manuals and safety checklists.',
      'Deploy smart demand-forecasting models to optimize prep sheets and reduce food waste.',
      'Automate recipe scaling and cost margins calculation via specialized spreadsheets.'
    ]
  },
  'catering coordinator': {
    category: 'Catering & Sales',
    automationRisk: 0.70,
    currentLiteracy: 'Medium',
    hitlTitle: 'AI-Powered Event Intake Specialist',
    impact: '75% reduction in manual menu quoting and client follow-up loops.',
    trainingWeeks: 4,
    skillsNeeded: ['RAG Quote Calculators', 'CRM Integration Pipelines', 'Drafting Automation'],
    transitionSteps: [
      'Deploy interactive catering quote estimators to capture high-intent leads.',
      'Configure automated booking calendars and SMS reservation follow-ups.',
      'Use LLM drafts to customize event proposals, dietary sheets, and client agreements.',
      'Manage client feedback loops and automate survey routing for review acquisition.'
    ]
  },
  // Support
  'customer support lead': {
    category: 'Customer Experience',
    automationRisk: 0.65,
    currentLiteracy: 'Medium',
    hitlTitle: 'AI Customer Operations Auditor',
    impact: '70% reduction in manual tier-1 ticket drafting.',
    trainingWeeks: 4,
    skillsNeeded: ['AI Chatbot Instruction Tuning', 'Sentiment Trend Analytics', 'Data Security Compliance'],
    transitionSteps: [
      'Learn to construct system-level customer support personas.',
      'Configure auto-reply escalation rules and prompt templates.',
      'Audit AI chat logs daily for accuracy and tone brand compliance.',
      'Train staff on managing AI failure modes and custom overrides.'
    ]
  },
  'customer support representative': {
    category: 'Customer Experience',
    automationRisk: 0.85,
    currentLiteracy: 'Low',
    hitlTitle: 'AI Helpdesk Trainer & Live Escalator',
    impact: '85% offloading of basic ticket answering.',
    trainingWeeks: 6,
    skillsNeeded: ['Prompt Engineering Basics', 'Live Chat Triage Management', 'Macro Writing'],
    transitionSteps: [
      'Transition from typing replies to selecting and refining AI draft responses.',
      'Act as the live fallback coordinator when AI hits low confidence scores.',
      'Flag recurring customer queries to expand the AI core knowledge base.',
      'Establish brand safety validation parameters for AI responses.'
    ]
  },
  'front desk representative': {
    category: 'Administration',
    automationRisk: 0.70,
    currentLiteracy: 'Low',
    hitlTitle: 'Digital Patient Flow Coordinator',
    impact: '60% booking and phone check-in task automation.',
    trainingWeeks: 5,
    skillsNeeded: ['Scheduling API Dashboards', 'AI Calendar Optimization Tools', 'Client Care Relations'],
    transitionSteps: [
      'Onboard conversational voice AI for inbound phone answering.',
      'Configure auto-booking systems and SMS appointment confirm queues.',
      'Focus strictly on direct client check-in experiences and specialized escalations.',
      'Manage scheduling conflict logs resolved by the AI router.'
    ]
  },

  // Admin / Operations
  'front desk receptionist': {
    category: 'Administration',
    automationRisk: 0.75,
    currentLiteracy: 'Low',
    hitlTitle: 'Digital Operations Coordinator',
    impact: '65% offload of calendar and client data-entry tasks.',
    trainingWeeks: 5,
    skillsNeeded: ['Automation Platforms (Zapier)', 'AI Voice Assistant Handlers', 'Conflict Resolution'],
    transitionSteps: [
      'Integrate AI-driven calendar booking pipelines and automated phone filters.',
      'Monitor AI automated meeting scheduler logs for scheduling collisions.',
      'Transition to an office environment host and complex operations coordinator.',
      'Establish digital data routing templates using basic spreadsheet automation.'
    ]
  },
  'practice administrator': {
    category: 'Administration',
    automationRisk: 0.40,
    currentLiteracy: 'Medium',
    hitlTitle: 'AI Operations Director',
    impact: '45% acceleration in scheduling, payroll audits, and inventory logs.',
    trainingWeeks: 4,
    skillsNeeded: ['Business Process Automation', 'AI Vendor Procurement', 'Metric Analytics'],
    transitionSteps: [
      'Automate monthly scheduling roster generation using heuristic AI sheets.',
      'Use LLMs to draft initial vendor contract reviews and staff newsletters.',
      'Audit AI-generated payroll sheets and inventory shortage indicators.',
      'Evaluate third-party AI software integrations for privacy regulations compliance.'
    ]
  },
  'billing specialist': {
    category: 'Operations & Finance',
    automationRisk: 0.80,
    currentLiteracy: 'Low',
    hitlTitle: 'AI Medical Coding & Claims Auditor',
    impact: '80% automated coding accuracy and draft claims generation.',
    trainingWeeks: 8,
    skillsNeeded: ['Medical Coding Knowledge bases', 'AI OCR Claim Reconciliation', 'Regulatory Compliance'],
    transitionSteps: [
      'Deploy AI OCR claims scanners to parse medical/dental notes.',
      'Review AI generated ICD codes for accuracy before portal submission.',
      'Resolve billing discrepancies flagged as high-risk by the AI validator.',
      'Run automated reports on insurance collection recovery rates.'
    ]
  },
  'patient billing coordinator': {
    category: 'Operations & Finance',
    automationRisk: 0.82,
    currentLiteracy: 'Low',
    hitlTitle: 'AI Billing Lifecycle Manager',
    impact: '80% claim review and spreadsheet parsing automation.',
    trainingWeeks: 7,
    skillsNeeded: ['OCR Document Audits', 'Structured Billing Engines', 'Client Payment Strategy'],
    transitionSteps: [
      'Transition from manually typing ICD codes to auditing AI-generated claims.',
      'Utilize AI billing engines to scan patient payment logs for outstanding debts.',
      'Focus staff time on resolving complex insurance denial disputes.',
      'Manage AI-triggered customer payment alert schedules.'
    ]
  },
  'operations manager': {
    category: 'Operations & Finance',
    automationRisk: 0.35,
    currentLiteracy: 'Medium',
    hitlTitle: 'AI Process Integration Manager',
    impact: '40% efficiency gains in report formatting and scheduling.',
    trainingWeeks: 4,
    skillsNeeded: ['Cross-functional Integrations', 'AI CRM Administration', 'Workflow Orchestration'],
    transitionSteps: [
      'Implement Zapier automation connections across CRM, email, and task boards.',
      'Deploy AI meeting summarizers to document action points.',
      'Focus efforts on strategic process redesigns and employee performance enablement.',
      'Conduct monthly reviews on AI tooling cost benefits.'
    ]
  },
  'executive assistant': {
    category: 'Administration',
    automationRisk: 0.78,
    currentLiteracy: 'Medium',
    hitlTitle: 'AI Business Partner & Chief of Staff Assistant',
    impact: '75% scheduling, report drafting, and email triaging offload.',
    trainingWeeks: 4,
    skillsNeeded: ['Advanced LLM Prompting', 'Action Tracker Automations', 'Calendar Management Systems'],
    transitionSteps: [
      'Employ custom GPT models trained on executive writing styles for email drafting.',
      'Use LLM summarize logs to digest long market briefs and outline action items.',
      'Manage multi-time-zone AI schedule routers for optimal calendars.',
      'Oversee executive-level travel logistics mapped by custom travel assistants.'
    ]
  },

  // Marketing & Growth
  'marketing coordinator': {
    category: 'Marketing & Sales',
    automationRisk: 0.72,
    currentLiteracy: 'Medium',
    hitlTitle: 'AI Content Director & Ad Campaign Overseer',
    impact: '70% draft copy, social layout, and ad segment creation automation.',
    trainingWeeks: 4,
    skillsNeeded: ['Generative Media Synthesis', 'A/B Test Campaign Tuning', 'SEO Analytics Platforms'],
    transitionSteps: [
      'Transition from writing baseline blog posts to generating SEO prompts in LLMs.',
      'Review AI generated social media visual ideas for brand guideline fits.',
      'Manage automated ad-targeting loops on Meta and Google Ads managers.',
      'Track data performance logs and feedback loops to train AI content models.'
    ]
  },
  'product marketing manager': {
    category: 'Marketing & Sales',
    automationRisk: 0.45,
    currentLiteracy: 'High',
    hitlTitle: 'AI Marketing Strategist & Brand Director',
    impact: '50% faster competitor analysis and content production cycles.',
    trainingWeeks: 3,
    skillsNeeded: ['AI Brand Safety Constraints', 'Target Audience Prompt Modeling', 'Strategic ROI Analytics'],
    transitionSteps: [
      'Feed AI scrapers competitor landing pages to analyze messaging gaps.',
      'Act as the chief editor and brand guardian for all AI content lines.',
      'Coordinate marketing automation workflows between HubSpot and custom APIs.',
      'Structure high-converting content outlines for LLM generators to execute.'
    ]
  },

  // Tech / Specialists
  'e-commerce manager': {
    category: 'Technology & Growth',
    automationRisk: 0.50,
    currentLiteracy: 'Medium',
    hitlTitle: 'AI Retail Operations Director',
    impact: '60% faster product updates, description edits, and sales analytics.',
    trainingWeeks: 4,
    skillsNeeded: ['No-Code API Connections', 'AI Product Listing Generators', 'Data Auditing'],
    transitionSteps: [
      'Deploy automated AI engines to write SEO-optimized product copy.',
      'Leverage AI inventory monitors to auto-restock items from suppliers.',
      'Review AI-driven user behavior maps to customize website conversion layout.',
      'Implement smart recommendation widgets on the Shopify store storefront.'
    ]
  },
  'technical support specialist': {
    category: 'Technology & Growth',
    automationRisk: 0.70,
    currentLiteracy: 'High',
    hitlTitle: 'AI Helpdesk Admin & Solution Engineer',
    impact: '60% offloading of basic ticket triage and QA diagnostics.',
    trainingWeeks: 3,
    skillsNeeded: ['Vector Knowledgebase Tuning', 'API Log Diagnostics', 'Security Guardrail Setup'],
    transitionSteps: [
      'Maintain and curate the vector database / RAG model for customer bots.',
      'Audit AI code snippet generators and troubleshooting guides for syntax safety.',
      'Transition to solving highly critical, multi-system enterprise bugs.',
      'Review security sandboxes of customer portal API endpoints.'
    ]
  },
  'junior associate': {
    category: 'Professional Staff',
    automationRisk: 0.75,
    currentLiteracy: 'Medium',
    hitlTitle: 'AI Research Analyst',
    impact: '70% research compilation and synthesis automation.',
    trainingWeeks: 5,
    skillsNeeded: ['Retrieval-Augmented Web Scrapers', 'AI Report Builders', 'Synthesis Verification'],
    transitionSteps: [
      'Replace manual web searches with web-connected AI search tools.',
      'Compile findings into structured brief templates generated by LLMs.',
      'Fact-check all claims, citations, and data points produced by AI tools.',
      'Focus work on strategic client synthesis and context application.'
    ]
  },
  'field service coordinator': {
    category: 'Operations',
    automationRisk: 0.80,
    currentLiteracy: 'Medium',
    hitlTitle: 'AI Operations Auditor & Dispatcher',
    impact: '75% reduction in manual dispatch routing and coordination loops.',
    trainingWeeks: 4,
    skillsNeeded: ['SLA Optimization Matrices', 'Twilio Call-Fielding Management', 'Conflict Resolution'],
    transitionSteps: [
      'Integrate the Twilio 24/7 call fielding receptor console for incoming service calls.',
      'Establish automated technician dispatch rules based on location and parts availability.',
      'Review automated routing schedules for conflict resolution or priority updates.',
      'Upskill to monitor network service-level agreements (SLAs) directly.'
    ]
  },
  'procurement specialist': {
    category: 'Operations & Finance',
    automationRisk: 0.75,
    currentLiteracy: 'Low',
    hitlTitle: 'AI Inventory Procurement Auditor',
    impact: '80% automated invoice verification and purchase order matching.',
    trainingWeeks: 6,
    skillsNeeded: ['OCR Document Reconciliation', 'ERP Sourcing Connectors', 'Contract Auditing'],
    transitionSteps: [
      'Deploy AI OCR parsers to ingest supplier component invoices and verify PO details.',
      'Validate ledger entries drafted automatically by n8n before pushing to QuickBooks.',
      'Monitor supply level alerts triggered by the automated inventory grid.',
      'Review high-value vendor contract proposals generated by LLM assistants.'
    ]
  },
  'rfp proposal specialist': {
    category: 'Marketing & Sales',
    automationRisk: 0.70,
    currentLiteracy: 'Medium',
    hitlTitle: 'AI RFP Technical Proposal Director',
    impact: '80% reduction in manual proposal writing and RFP response compilation.',
    trainingWeeks: 5,
    skillsNeeded: ['RAG Database Construction', 'Prompt Injection Defense', 'Federal Proposal Frameworks'],
    transitionSteps: [
      'Onboard past winning proposals and grid designs into the Dify.ai RAG knowledge base.',
      'Use LLMs to draft initial technical RFP bid responses and compliance certificates.',
      'Review and fact-check all data parameters and engineering quotes compiled by AI.',
      'Focus on customizing partner relations and negotiating municipality lease terms.'
    ]
  },
  'grid compliance officer': {
    category: 'Administration',
    automationRisk: 0.35,
    currentLiteracy: 'High',
    hitlTitle: 'AI Grid Compliance & Regulatory Auditor',
    impact: '40% acceleration in compliance reporting and audit verification.',
    trainingWeeks: 4,
    skillsNeeded: ['Regulatory Database Integrators', 'Security Token Governance', 'Audit Trail Monitoring'],
    transitionSteps: [
      'Deploy automated monitors tracking NERC/FERC rules and local utility tariff databases.',
      'Audit the local container database security credentials and KMS sandboxes.',
      'Coordinate safety compliance declarations and certification logs via automated trackers.',
      'Oversee corporate policies alignment with state and federal clean energy mandates.'
    ]
  }
};

/**
 * Generic baseline role data used when scraped roles do not match database
 */
const DEFAULT_ROLE_TEMPLATE = {
  category: 'Operations',
  automationRisk: 0.60,
  currentLiteracy: 'Medium',
  hitlTitle: 'AI Operations Specialist',
  impact: '50% repetitive administrative task automation.',
  trainingWeeks: 4,
  skillsNeeded: ['Generative Office Productivity Tools', 'Fact-checking & Auditing', 'Process Automation'],
  transitionSteps: [
    'Analyze recurring operations to pinpoint highly repetitive subtasks.',
    'Formulate targeted prompts for drafting reports, emails, and schedules.',
    'Review all AI outputs for accuracy, compliance, and logical errors.',
    'Coordinate tool output with other team members to optimize joint workflows.'
  ]
};

/**
 * Analyzes scraped team profiles and maps out custom HITL AI Transition blueprint
 */
function analyzeWorkforce(scraperData) {
  const { rawTeamData, rawJobPostings, vertical, domain, businessName } = scraperData;
  
  const domainLower = (domain || '').toLowerCase();
  const nameLower = (businessName || '').toLowerCase();
  const isFoodService = ['bread', 'catering', 'restaurant', 'food', 'deli', 'cafe', 'kitchen', 'bakery', 'brew', 'coffee', 'bites', 'eats', 'grill', 'menu'].some(k => domainLower.includes(k) || nameLower.includes(k));
  
  const analyzedRoles = [];
  let totalRisk = 0;
  let totalLiteracyVal = 0;
  
  const literacyMap = { 'Low': 40, 'Medium': 70, 'High': 95 };

  // 1. Process Team Members
  rawTeamData.forEach(member => {
    const roleLower = member.role.toLowerCase();
    
    // Find closest template matching role string
    let templateKey = Object.keys(ROLE_TEMPLATES).find(k => roleLower.includes(k) || k.includes(roleLower));
    
    // Fallback: search by keywords in the vertical
    if (!templateKey) {
      if (roleLower.includes('chef') || roleLower.includes('kitchen') || roleLower.includes('cook')) {
        templateKey = 'kitchen manager';
      } else if (roleLower.includes('catering') || roleLower.includes('event')) {
        templateKey = 'catering coordinator';
      } else if (roleLower.includes('general manager') || roleLower.includes('restaurant manager') || roleLower.includes('store manager') || roleLower.includes('owner')) {
        templateKey = 'general manager';
      } else if (roleLower.includes('founder') || roleLower.includes('ceo') || roleLower.includes('director') || roleLower.includes('partner')) {
        templateKey = 'practice administrator'; // Strategic low-risk roles
      } else if (roleLower.includes('support') || roleLower.includes('service') || roleLower.includes('chat')) {
        templateKey = 'customer support representative';
      } else if (roleLower.includes('assistant') || roleLower.includes('clerk') || roleLower.includes('receptionist')) {
        templateKey = 'front desk receptionist';
      } else if (roleLower.includes('billing') || roleLower.includes('finance') || roleLower.includes('bookkeeper')) {
        templateKey = 'patient billing coordinator';
      } else if (roleLower.includes('market') || roleLower.includes('social') || roleLower.includes('content')) {
        templateKey = 'marketing coordinator';
      } else if (roleLower.includes('dispatch') || roleLower.includes('route') || roleLower.includes('coordinate')) {
        templateKey = 'field service coordinator';
      } else if (roleLower.includes('procure') || roleLower.includes('sourcing') || roleLower.includes('inventory')) {
        templateKey = 'procurement specialist';
      } else if (roleLower.includes('proposal') || roleLower.includes('rfp') || roleLower.includes('bid')) {
        templateKey = 'rfp proposal specialist';
      } else if (roleLower.includes('compliance') || roleLower.includes('safety') || roleLower.includes('auditor')) {
        templateKey = 'grid compliance officer';
      }
    }

    const template = templateKey ? ROLE_TEMPLATES[templateKey] : DEFAULT_ROLE_TEMPLATE;
    const risk = template.automationRisk;
    const literacy = template.currentLiteracy;
    
    totalRisk += risk;
    totalLiteracyVal += literacyMap[literacy];

    // Build the upskilled profile
    analyzedRoles.push({
      employeeName: member.name,
      originalRole: member.role,
      bio: member.bio,
      category: template.category,
      automationRiskScore: Math.round(risk * 100),
      literacyLevel: literacy,
      hitlRole: template.hitlTitle,
      impactStatement: template.impact,
      trainingDurationWeeks: template.trainingWeeks,
      coreSkillsToAcquire: template.skillsNeeded,
      transitionBlueprint: template.transitionSteps
    });
  });

  // If no team members were scraped, construct standard baseline team for the vertical
  if (analyzedRoles.length === 0) {
    const baselineRoles = Object.keys(ROLE_TEMPLATES).filter(k => {
      if (vertical === 'E-Commerce & Retail') {
        if (isFoodService) {
          return ['general manager', 'kitchen manager', 'catering coordinator'].includes(k);
        }
        return ['customer support representative', 'marketing coordinator', 'e-commerce manager'].includes(k);
      } else if (vertical === 'Technology & SaaS') {
        return ['customer support lead', 'product marketing manager', 'technical support specialist', 'executive assistant'].includes(k);
      } else if (vertical === 'Healthcare & Wellness') {
        return ['front desk representative', 'practice administrator', 'patient billing coordinator'].includes(k);
      } else if (vertical === 'Sustainable Infrastructure & Green Tech') {
        return ['field service coordinator', 'procurement specialist', 'rfp proposal specialist', 'grid compliance officer'].includes(k);
      } else {
        return ['operations manager', 'junior associate', 'executive assistant'].includes(k);
      }
    });

    const mockNames = ['Jane Miller', 'Robert Carter', 'Sophia Brooks', 'Nathan Reed'];
    baselineRoles.forEach((roleKey, idx) => {
      const template = ROLE_TEMPLATES[roleKey];
      const risk = template.automationRisk;
      const literacy = template.currentLiteracy;
      totalRisk += risk;
      totalLiteracyVal += literacyMap[literacy];

      analyzedRoles.push({
        employeeName: mockNames[idx] || 'Team Member ' + (idx + 1),
        originalRole: roleKey.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '),
        bio: `Assists ${vertical} operational success.`,
        category: template.category,
        automationRiskScore: Math.round(risk * 100),
        literacyLevel: literacy,
        hitlRole: template.hitlTitle,
        impactStatement: template.impact,
        trainingDurationWeeks: template.trainingWeeks,
        coreSkillsToAcquire: template.skillsNeeded,
        transitionBlueprint: template.transitionSteps
      });
    });
  }

  const teamCount = analyzedRoles.length;
  const avgAutomationRisk = Math.round((totalRisk / teamCount) * 100);
  const avgDigitalLiteracy = Math.round(totalLiteracyVal / teamCount);

  // 2. Calculate Job Readiness Score (0-100)
  // Higher literacy increases score, high automation risk decreases readiness unless trained
  // Job Readiness = Literacy - (Risk * (100 - Literacy)/2)
  let rawReadiness = avgDigitalLiteracy - (avgAutomationRisk * (100 - avgDigitalLiteracy) * 0.005);
  const jobReadinessScore = Math.min(100, Math.max(10, Math.round(rawReadiness)));

  // 3. Process open positions to analyze growth requirements
  const analyzedJobs = rawJobPostings.map(job => {
    let skillShift = 'Focus recruitment on individuals capable of validating and checking AI output rather than manual creation.';
    if (job.title.toLowerCase().includes('support') || job.title.toLowerCase().includes('service')) {
      skillShift = 'Require basic LLM prompt familiarity and chat dashboard triage experiences.';
    } else if (job.title.toLowerCase().includes('billing') || job.title.toLowerCase().includes('finance')) {
      skillShift = 'Prioritize spreadsheet macro automation and automated OCR check audit capabilities.';
    } else if (job.title.toLowerCase().includes('write') || job.title.toLowerCase().includes('content')) {
      skillShift = 'Look for editors capable of setting style guide weights and SEO keywords in AI generative tools.';
    }

    return {
      title: job.title,
      description: job.description,
      riskLevel: job.title.toLowerCase().includes('clerk') || job.title.toLowerCase().includes('entry') ? 'High' : 'Medium',
      upskilledRecruitmentStrategy: skillShift
    };
  });

  // 4. Construct department-level statistics
  const departmentStats = {};
  analyzedRoles.forEach(role => {
    if (!departmentStats[role.category]) {
      departmentStats[role.category] = { count: 0, sumRisk: 0, highRiskCount: 0 };
    }
    departmentStats[role.category].count += 1;
    departmentStats[role.category].sumRisk += role.automationRiskScore;
    if (role.automationRiskScore >= 70) {
      departmentStats[role.category].highRiskCount += 1;
    }
  });

  const departments = Object.keys(departmentStats).map(name => {
    const stats = departmentStats[name];
    return {
      name,
      staffCount: stats.count,
      averageRisk: Math.round(stats.sumRisk / stats.count),
      highAutomationVuln: stats.highRiskCount,
      transitionPriority: stats.highRiskCount > 0 ? 'High Priority' : 'Standard'
    };
  });

  return {
    summary: {
      totalStaffAudited: teamCount,
      averageAutomationExposure: avgAutomationRisk,
      digitalLiteracyRating: avgDigitalLiteracy,
      jobReadinessScore: jobReadinessScore,
      status: jobReadinessScore > 75 ? 'AI Advantage' : jobReadinessScore > 50 ? 'Transition Ready' : 'Vulnerable'
    },
    roles: analyzedRoles,
    hiringStrategy: analyzedJobs,
    departments,
    timeframeMilestones: {
      immediate: {
        range: '1 - 30 Days',
        title: 'Automation Alignment & Tool Auditing',
        actions: [
          'Introduce corporate-wide Generative AI policy guidelines.',
          'Onboard basic AI summarization tools and office assistants.',
          'Track active time sinks in support and administration queues.'
        ]
      },
      midTerm: {
        range: '31 - 90 Days',
        title: 'HITL Training & Interface Pilots',
        actions: [
          'Launch prompt training courses customized for target roles.',
          'Pilot a conversational AI support interface for tier-1 customer queries.',
          'Conduct initial testing on OCR scanning for billing pipelines.'
        ]
      },
      longTerm: {
        range: '90+ Days',
        title: 'Full Human-in-the-Loop Integrations',
        actions: [
          'Promote upskilled operators to AI Auditors and workflow designers.',
          'Scale custom integrations (Zapier automation and RAG databases).',
          'Audit and re-evaluate efficiency metrics to measure structural growth.'
        ]
      }
    }
  };
}

module.exports = {
  analyzeWorkforce
};
