# ensure_server_running.ps1 -- Auto-generated by install_task_scheduler.ps1
# Starts server.js only if port 3003 is not already in use.
$port = 3003
$listening = netstat -ano 2>null | Select-String ":$port\s+.*LISTENING"
if ($listening) {
    Write-Host "[AutoStart] server.js already running on port $port. Skipping."
    exit 0
}
Write-Host "[AutoStart] server.js not detected. Starting now..."
$serverJs = Join-Path $PSScriptRoot "server.js"
$nodeExe  = (Get-Command node).Source
Start-Process $nodeExe -ArgumentList "$serverJs" -WorkingDirectory $PSScriptRoot -WindowStyle Hidden
Write-Host "[AutoStart] server.js launched in background."
