<#
.SYNOPSIS
    Install AiWorXmiths Social Media Auto-Poster as Windows Task Scheduler jobs.
.DESCRIPTION
    Registers two scheduled tasks:
      1. AiWorXmiths-SocialMediaScheduler  - fires scheduler_daemon.js every 15 minutes
      2. AiWorXmiths-ServerAutoStart       - restarts server.js on login if not running
    Run from a PowerShell prompt (no admin required for current-user tasks).
    To uninstall: .\uninstall_task_scheduler.ps1
.NOTES
    Author : CONVERGENCE-Ai / AiWorXmiths
#>

$ScriptDir     = $PSScriptRoot
$AgentDir      = Resolve-Path (Join-Path $ScriptDir "..\aiwx-social-media-agent")
$NodeExe       = (Get-Command node -ErrorAction Stop).Source
$DaemonScript  = Join-Path $ScriptDir "scheduler_daemon.js"
$ServerScript  = Join-Path $ScriptDir "server.js"
$LogDir        = Join-Path $AgentDir "logs"

# Ensure log directory exists
if (-not (Test-Path $LogDir)) {
    New-Item -ItemType Directory -Path $LogDir -Force | Out-Null
}

Write-Host ""
Write-Host "===================================================" -ForegroundColor Cyan
Write-Host "  AiWorXmiths Task Scheduler Installer" -ForegroundColor Cyan
Write-Host "===================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Node.js  : $NodeExe" -ForegroundColor Gray
Write-Host "  Daemon   : $DaemonScript" -ForegroundColor Gray
Write-Host "  Server   : $ServerScript" -ForegroundColor Gray
Write-Host "  Log Dir  : $LogDir" -ForegroundColor Gray
Write-Host ""

# ============================================================
# Task 1: Campaign Scheduler Daemon (every 15 minutes)
# ============================================================
$SchedulerTaskName = "AiWorXmiths-SocialMediaScheduler"

Write-Host "[1/2] Registering Campaign Scheduler Task..." -ForegroundColor Yellow

Unregister-ScheduledTask -TaskName $SchedulerTaskName -Confirm:$false -ErrorAction SilentlyContinue

$SchedulerAction = New-ScheduledTaskAction `
    -Execute $NodeExe `
    -Argument "`"$DaemonScript`"" `
    -WorkingDirectory $ScriptDir

$RepeatTrigger = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) `
    -RepetitionInterval (New-TimeSpan -Minutes 15) `
    -RepetitionDuration (New-TimeSpan -Days 3650)

$SchedulerSettings = New-ScheduledTaskSettingsSet `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 10) `
    -MultipleInstances IgnoreNew `
    -StartWhenAvailable

$SchedulerPrincipal = New-ScheduledTaskPrincipal `
    -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive `
    -RunLevel Limited

Register-ScheduledTask `
    -TaskName $SchedulerTaskName `
    -Action $SchedulerAction `
    -Trigger $RepeatTrigger `
    -Settings $SchedulerSettings `
    -Principal $SchedulerPrincipal `
    -Description "AiWorXmiths: Checks campaign_schedule.json every 15 min and publishes approved posts." `
    -Force | Out-Null

Write-Host "  OK: '$SchedulerTaskName' registered (fires every 15 minutes)" -ForegroundColor Green

# ============================================================
# Task 2: Server Auto-Start on Login
# ============================================================
$ServerTaskName = "AiWorXmiths-ServerAutoStart"

Write-Host "[2/2] Registering Server Auto-Start Task..." -ForegroundColor Yellow

Unregister-ScheduledTask -TaskName $ServerTaskName -Confirm:$false -ErrorAction SilentlyContinue

# Write the wrapper script that checks if port 3003 is occupied before starting
$ServerWrapperPath = Join-Path $ScriptDir "ensure_server_running.ps1"
$WrapperContent = @"
# ensure_server_running.ps1 -- Auto-generated by install_task_scheduler.ps1
# Starts server.js only if port 3003 is not already in use.
`$port = 3003
`$listening = netstat -ano 2>null | Select-String ":`$port\s+.*LISTENING"
if (`$listening) {
    Write-Host "[AutoStart] server.js already running on port `$port. Skipping."
    exit 0
}
Write-Host "[AutoStart] server.js not detected. Starting now..."
`$serverJs = Join-Path `$PSScriptRoot "server.js"
`$nodeExe  = (Get-Command node).Source
Start-Process `$nodeExe -ArgumentList `"`$serverJs`" -WorkingDirectory `$PSScriptRoot -WindowStyle Hidden
Write-Host "[AutoStart] server.js launched in background."
"@
Set-Content -Path $ServerWrapperPath -Value $WrapperContent -Encoding UTF8

$ServerAction = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-ExecutionPolicy Bypass -WindowStyle Hidden -File `"$ServerWrapperPath`"" `
    -WorkingDirectory $ScriptDir

$ServerTrigger = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\$env:USERNAME"

$ServerSettings = New-ScheduledTaskSettingsSet `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 2) `
    -MultipleInstances IgnoreNew `
    -StartWhenAvailable

$ServerPrincipal = New-ScheduledTaskPrincipal `
    -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive `
    -RunLevel Limited

Register-ScheduledTask `
    -TaskName $ServerTaskName `
    -Action $ServerAction `
    -Trigger $ServerTrigger `
    -Settings $ServerSettings `
    -Principal $ServerPrincipal `
    -Description "AiWorXmiths: Ensures the local Node.js API server (port 3003) starts automatically at login." `
    -Force | Out-Null

Write-Host "  OK: '$ServerTaskName' registered (fires at login)" -ForegroundColor Green

# ============================================================
# Summary
# ============================================================
Write-Host ""
Write-Host "===================================================" -ForegroundColor Green
Write-Host "  Installation Complete!" -ForegroundColor Green
Write-Host "===================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Tasks registered:" -ForegroundColor White
Write-Host "    * $SchedulerTaskName" -ForegroundColor Cyan
Write-Host "      Fires scheduler_daemon.js every 15 minutes." -ForegroundColor Gray
Write-Host "    * $ServerTaskName" -ForegroundColor Cyan
Write-Host "      Starts server.js automatically at login." -ForegroundColor Gray
Write-Host ""
Write-Host "  To manually run the scheduler now:" -ForegroundColor White
Write-Host "    node `"$DaemonScript`"" -ForegroundColor Yellow
Write-Host ""
Write-Host "  To uninstall: .\uninstall_task_scheduler.ps1" -ForegroundColor Gray
Write-Host ""
